### ISSUE TITLE
pkginfo key description should be type <type 'str'>, not type <type 'unicode'>

### ISSUE THREAD

**Issue by macmule** [homebysix/pre-commit-macadmin#25]
Running `pre-commit run --all-files` on dataJAR-recipes resulted in:

> AirParrot 2-Trial/AirParrot 2-Trial.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> Backup Manager/Backup Manager.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> BlueGriffon/BlueGriffon.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> BoxDrive/BoxDrive.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> Cubase 9/Cubase 9.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> FlashPrint/FlashPrint.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> Google Backup and Sync/Google Backup and Sync.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> Malwarebytes Breach Remediation-Command Line Interface/Malwarebytes Breach Remediation-Command Line Interface.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> Microsoft OneNote 365/Microsoft OneNote 365.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> Noun Project/Noun Project.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> QLab4/QLab4.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> Racket 6/Racket 6.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> Racket 7/Racket 7.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> renpy 6/renpy 6.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> renpy 7/renpy 7.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> Suitcase Fusion 9/Suitcase Fusion 9.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> SwitchResX4-Trial/SwitchResX4-Trial.munki.recipe: pkginfo key developer should be type <type 'str'>, not type <type 'unicode'>
> US-20x20_SettingsPanel/US-20x20_SettingsPanel.download.recipe: recipe identifier does not start with "com.github.dataJAR-recipes."
> US-20x20_SettingsPanel/US-20x20_SettingsPanel.munki.recipe: recipe identifier does not start with "com.github.dataJAR-recipes."
> US-20x20_SettingsPanel/US-20x20_SettingsPanel.pkg.recipe: recipe identifier does not start with "com.github.dataJAR-recipes."
> WaveLab Elements 9.5/WaveLab Elements 9.5.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> WaveLab LE 9.5/WaveLab LE 9.5.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>
> WaveLab LE 9/WaveLab LE 9.munki.recipe: pkginfo key description should be type <type 'str'>, not type <type 'unicode'>

These are all valid XML, & some are just due to `’` being used in place of `'`.. I think this is too harsh

**Comment by homebysix** [comment]
Good catch — I've also seen this error, and will look into it.

**Comment by homebysix** [comment]
Try updating to v1.2.2 and `pre-commit run --all files` again?
