### ISSUE TITLE
Adjust profile manifest requirements for `pfm_name` and `pfm_type`

### ISSUE THREAD

**Issue by homebysix** [homebysix/pre-commit-macadmin#54]
Copying over @apizz's comments from [this pull request](https://github.com/ProfileCreator/ProfileManifests/pull/495#issuecomment-1018183349).

>One thing I did discover is that while it will fail to let me commit if I remove the pfm_type key it will notably commit just fine without a pfm_name key. It's required for top-level keys (first layer of pfm_subkeys) but not for all items in the layer below that (thinking of an array with a subkey that's a string). Not sure how difficult it would be to add this just at the layer we need, but if we could get that included as a required key that would be awesome!

**Comment by homebysix** [comment]
@apizz Just to clarify: `pfm_name` should be required for the first level of `pfm_subkeys`, but is not required deeper than that?

**Comment by apizz** [comment]
So I guess this is less nuanced than I thought. pfm_name is required for all first level subkeys from the top / root level manifest. After that, it is only for additional pdm_subkeys layers that do not have a parent preference where pfm_type is array.

Does that make sense?

**Comment by relgit** [comment]
I think you had an extra _not_ sneak in there by mistake @apizz 😅

Let's go by this rule of thumb, from ProfileManifests' wiki: `pfm_name` is required for every preference key except immediate descendants of keys whose`pfm_type` is `array`.

**Comment by apizz** [comment]
The problem is that if we have an array of dictionaries then there will be key value pairs in the dictionary that will need `pfm_name`

**Comment by relgit** [comment]
If you think about it, only the dictionary is an immediate descendant of the array - not its pairs. So the need for `pfm_name` on these pairs is respected.
